# Generated by Django 4.2.7 on 2024-01-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soninha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
