# Generated by Django 4.2.7 on 2024-02-29 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soninha', '0002_alter_user_avatar_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_distance', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('hours_played', models.IntegerField()),
                ('matches_classic', models.IntegerField()),
                ('matches_coop', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soninha.user')),
            ],
        ),
    ]
