# Generated by Django 4.2.7 on 2024-02-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soninha', '0003_rename_avatar_image_url_user_intra_cdn_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_distance', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('hours_played', models.IntegerField(default=0)),
                ('matches_classic', models.IntegerField(default=0)),
                ('matches_coop', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soninha.user')),
            ],
        ),
    ]
