version: '3'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    restart: always
    networks:
      - ft_transcendence

  django:
    image: django
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    build: ./transcendence-core/
    ports:
      - '8000:8000'
    restart: always
    networks:
      - ft_transcendence
    depends_on:
      - postgres

networks:
  ft_transcendence:
    driver: bridge
    name: inception
