services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres-vol:/var/lib/postgresql
    restart: always
    networks:
      - transcendence

  api:
    container_name: api
    depends_on:
      - postgres
    build:
      context: ./api/
    ports:
      - 3000:3000
    networks:
      - transcendence
    restart: always
    volumes:
      - ./api:/usr/src/app

volumes:
  postgres-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/goinfre/ft_transcendence_data'

networks:
  transcendence:
    driver: bridge
    name: transcendence
