version: '3'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    restart: always
    ports:
        - '5432:5432'
    networks:
      - ft_transcendence
    volumes:
      - postgres-vol:/var/lib/postgresql

  django:
    image: django
    container_name: django
    command: python manage.py runserver_plus --cert-file cert.pem --key-file key.pem 0.0.0.0:8000
    build: ./transcendence-core/
    ports:
      - '8000:8000'
    restart: always
    networks:
      - ft_transcendence
    depends_on:
      - postgres

networks:
  ft_transcendence:
    driver: bridge
    name: ft_transcendence

volumes:
  postgres-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/goinfre/ft_transcendence_data'
