version: '3'
services:
  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    restart: always
    ports:
        - '8545:8545'
    networks:
      - ft_transcendence
  # ganache:
  #   image: ganache:latest
  #   container_name: ganache
  #   restart: always
  #   build: 
  #     context: ./ganache
  #   ports:
  #       - '8545:8545'
  #   networks:
  #     - ft_transcendence
  #   volumes:
  #     - ganache-vol:/ganache_data

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file: .env  
    restart: always
    ports:
        - '${POSTGRES_PORT}:5432'
    networks:
      - ft_transcendence
    volumes:
      - postgres-vol:/var/lib/postgresql

  django:
    image: django
    container_name: django
    command: python manage.py runserver_plus --cert-file cert.pem --key-file key.pem 0.0.0.0:8000
    build: ./
    ports:
      - '8000:8000'
    restart: always
    networks:
      - ft_transcendence
    depends_on:
      - postgres

networks:
  ft_transcendence:
    driver: bridge
    name: ft_transcendence

volumes:
  postgres-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/goinfre/ft_transcendence_data/postgres'
  ganache-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/goinfre/ft_transcendence_data/ganache'
