version: '3'

services: 
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    restart: always

  django:
    image: django
    build:
      context: ./transcendence-core/
    ports:
      - '8000:8000'
    restart: always
