version: '3'
services:
  postgres-transcendence:
    image: postgres:16-alpine
    container_name: postgres-transcendence
    env_file: .env  
    restart: always
    ports:
        - '${POSTGRES_PORT}:5432'
    networks:
      - ft_transcendence
    volumes:
      - postgres-vol:/var/lib/postgresql

  django-transcendence:
    image: django-transcendence
    container_name: django-postgres
    command: python manage.py runserver_plus --cert-file cert.pem --key-file key.pem 0.0.0.0:8000
    build: ./
    ports:
      - '8000:8000'
    restart: always
    networks:
      - ft_transcendence
    depends_on:
      - postgres-transcendence

networks:
  ft_transcendence:
    driver: bridge
    name: ft_transcendence

volumes:
  postgres-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/goinfre/ft_transcendence_data'
