version: '3'
services:
  ganache-transcendence:
    image: trufflesuite/ganache:latest
    container_name: ganache
    restart: always
    ports:
        - '8545:8545'
    networks:
      - ft_transcendence

  contract-deployer-transcendence:
    image: contract-deployer:latest
    container_name: contract-deployer
    networks:
      - ft_transcendence
    build: 
      context: ./truffle
    depends_on:
      - ganache-transcendence
    volumes:
      - ./truffle/tournament/build/contracts:/tournament/build/contracts

  postgres-transcendence:
    image: postgres:16-alpine
    container_name: postgres
    env_file: .env  
    restart: always
    ports:
        - '${POSTGRES_PORT}:5432'
    networks:
      - ft_transcendence
    volumes:
      - postgres-vol:/var/lib/postgresql

  django-transcendence:
    image: django
    container_name: django
    build: ./
    ports:
      - '8000:8000'
    restart: always
    networks:
      - ft_transcendence
    depends_on:
      - postgres-transcendence
      - contract-deployer-transcendence

networks:
  ft_transcendence:
    driver: bridge
    name: ft_transcendence

volumes:
  postgres-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/goinfre/ft_transcendence/postgres'
  ganache-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/goinfre/ft_transcendence/ganache'