# Generated by Django 4.2.7 on 2024-03-03 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soninha', '0004_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_played', models.FloatField(default=0)),
                ('coop_cumulative_ball_distance', models.FloatField(default=0)),
                ('classic_cumulative_ball_distance', models.FloatField(default=0)),
                ('coop_hits_record', models.IntegerField(default=0)),
                ('classic_victories', models.FloatField(default=0)),
                ('classic_oponents', models.ManyToManyField(related_name='opponents', to='soninha.user')),
                ('coop_companions', models.ManyToManyField(related_name='companions', to='soninha.user')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='soninha.user')),
            ],
        ),
    ]
