# Generated by Django 4.2.7 on 2024-03-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='vs_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
