# Generated by Django 4.2.7 on 2024-03-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_remove_score_vs_id_score_vs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.BooleanField(default=False),
        ),
    ]
