version: '3'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres-vol:/var/lib/postgresql
    restart: always
    networks:
      - transcendence

  ft_transcendence_dev:
    image: ft_transcendence_dev
    container_name: ft_transcendence_dev
    volumes:
      - ..:/workspaces/ft_transcendence:cached
    build: 
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - 3000:3000
      - 8000:3001
    networks:
      - transcendence

volumes:
  postgres-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/goinfre/ft_transcendence_data'

networks:
  transcendence:
    driver: bridge
    name: transcendence
