# Generated by Django 4.2.7 on 2023-11-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_intra', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=40)),
                ('avatar_image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
